
DOT = '1'
DASH = '111'
LETTER_PARTS_SPACE = '0'
LETTERS_SPACE = '000'
WORDS_SPACE = '0000000'
WHITE_SPACE = ' '


TEXT_TO_MORSE = {
    'A': DOT + LETTER_PARTS_SPACE + DASH,
    'B': DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT,
    'C': DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DOT,
    'D': DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT,
    'E': DOT,
    'F': DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DOT,
    'G': DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DOT,
    'H': DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT,
    'I': DOT + LETTER_PARTS_SPACE + DOT,
    'J': DOT + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH,
    'K': DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DASH,
    'L': DOT + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT,
    'M': DASH + LETTER_PARTS_SPACE + DASH,
    'N': DASH + LETTER_PARTS_SPACE + DOT,
    'O': DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH,
    'P': DOT + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DOT,
    'Q': DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DASH,
    'R': DOT + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DOT,
    'S': DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT,
    'T': DASH,
    'U': DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DASH,
    'V': DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DASH,
    'W': DOT + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH,
    'X': DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DASH,
    'Y': DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH,
    'Z': DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT,
    '2': DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH,
    '1': DOT + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH,
    '3': DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH,
    '4': DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DASH,
    '5': DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT,
    '6': DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT,
    '7': DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT,
    '8': DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DOT + LETTER_PARTS_SPACE + DOT,
    '9': DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DOT,
    '0': DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH + LETTER_PARTS_SPACE + DASH,
}

# traduzir texto para morse

def text_to_morse(text):
    words = text.upper().split(' ')
    morse_code = map(separate_word_in_morse, words)
    return WORDS_SPACE.join(morse_code)

# quebrar as palavras
def separate_word_in_morse(word):
    return LETTERS_SPACE.join(map(translate_char_to_morse,word))

# traduzir as letras para morse
def translate_char_to_morse(char):
    return TEXT_TO_MORSE[char]


# transformar morse para texto, quebrando de frase para palavra e então letrass

def morse_to_text(morse):
    
    text = ''
    words = morse.split(WORDS_SPACE)
    for word in words:
        letters = word.split(LETTERS_SPACE)
        for letter in letters:
            for c,m in TEXT_TO_MORSE.items():
                if letter == m:
                    text += c
            text += ''
        text += ' '
    return text
    